version: '3'
services:
  mysql:
    container_name: presta8-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
  mailcatcher:
    container_name: presta8-mailcatcher
    image: sj26/mailcatcher:latest
    ports:
      # - "21025:1025"
      - "21080:1080"
    networks:
      - prestashop_network

  prestashop:
    container_name: presta8-prestashop
    image: prestashop/prestashop:8.1.2
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8081:80
    volumes:
      - /home/ubuadmin/workspace/container_storage/pslast/:/var/www/html
      - ./conf_file/000-default.apache.80.and.8080.conf:/etc/apache2/sites-enabled/000-default.conf
    environment:
      DB_SERVER: presta8-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1
      PS_DEV_MODE: 1
      PS_DOMAIN: presta8:8081
    networks:
      - prestashop_network
networks:
    prestashop_network:
